version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: postgres_reclamtrip
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: reclamtrip
    ports:
      - '5472:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data
